import { Room } from './types';

export const rooms: Room[] = [
  {
    id: '1',
    name: 'Deluxe Ocean Suite',
    description: 'Experience the ultimate in coastal luxury. This expansive suite features a private balcony with panoramic ocean views, a king-sized bed, and a spa-inspired bathroom.',
    price: 350,
    capacity: 2,
    imageUrl: '/images/rooms/room%20ocean.jpg',
    slug: 'deluxe-ocean-suite',
    amenities: ['Ocean View', 'King Bed', 'Private Balcony', 'Jacuzzi', 'Free WiFi', 'Room Service'],
    featured: true,
  },
  {
    id: '2',
    name: 'Executive City Loft',
    description: 'Designed for the modern traveler, this loft offers floor-to-ceiling windows overlooking the city skyline, a dedicated workspace, and a smart entertainment system.',
    price: 280,
    capacity: 2,
    imageUrl: '/images/rooms/room%20city.jpg',
    slug: 'executive-city-loft',
    amenities: ['City View', 'Work Desk', 'Smart TV', 'High-Speed WiFi', 'Mini Bar', 'Coffee Machine'],
    featured: true,
  },
  {
    id: '3',
    name: 'Family Garden Villa',
    description: 'A sanctuary for families. Nestled in our tropical gardens, this villa features two bedrooms, a private patio, and direct access to the kids pool.',
    price: 450,
    capacity: 4,
    imageUrl: '/images/rooms/room%20garden.jpg',
    slug: 'family-garden-villa',
    amenities: ['Garden Access', '2 Bedrooms', 'Patio', 'Kitchenette', 'Kids Pool Access', 'Netflix'],
    featured: false,
  },
  {
    id: '4',
    name: 'Royal Presidential Penthouse',
    description: 'The crown jewel of our hotel. Spanning the entire top floor, this residence offers unmatched privacy, a personal butler, and a private rooftop infinity pool.',
    price: 1200,
    capacity: 6,
    imageUrl: '/images/rooms/room%20garden.jpg',
    slug: 'royal-presidential-penthouse',
    amenities: ['Infinity Pool', 'Butler Service', 'Private Elevator', 'Grand Piano', 'Full Kitchen', 'Sauna'],
    featured: true,
  },
  {
    id: '5',
    name: 'Riverside Bungalow',
    description: 'Escape to nature in this wooden bungalow perched right on the riverbank. Fall asleep to the sound of flowing water and wake up to bird songs.',
    price: 320,
    capacity: 2,
    imageUrl: '/images/rooms/room%20garden.jpg',
    slug: 'riverside-bungalow',
    amenities: ['River View', 'Outdoor Rain Shower', 'Hammock', 'Mosquito Netting', 'Tea Station', 'Yoga Mats'],
    featured: false,
  },
  {
    id: '6',
    name: 'Standard Twin Room',
    description: 'Comfortable and convenient, our Twin Room is perfect for friends or colleagues. Includes two plush queen beds and all modern necessities.',
    price: 180,
    capacity: 2,
    imageUrl: '/images/rooms/room%20garden.jpg',
    slug: 'standard-twin-room',
    amenities: ['2 Queen Beds', 'En-suite Shower', 'Ironing Board', 'TV', 'Free WiFi', 'Safe'],
    featured: false,
  },
  {
    id: '7',
    name: 'Honeymoon Cabana',
    description: 'A romantic hideaway designed for couples. Features a secluded location, rose petal turn-down service, and a complimentary bottle of champagne upon arrival.',
    price: 400,
    capacity: 2,
    imageUrl: '/images/rooms/room%20garden.jpg',
    slug: 'honeymoon-cabana',
    amenities: ['Secluded Location', 'Round Bed', 'Champagne Service', 'Mood Lighting', 'Bathtub', 'Sound System'],
    featured: true,
  },
  {
    id: '8',
    name: 'Compact Business Single',
    description: 'Efficient luxury for the solo traveler. A cozy space that maximizes functionality with a high-end ergonomic chair and blackout curtains for deep sleep.',
    price: 150,
    capacity: 1,
    imageUrl: '/images/rooms/room%20garden.jpg',
    slug: 'compact-business-single',
    amenities: ['Single Bed', 'Ergonomic Chair', 'Blackout Curtains', 'USB Charging Ports', 'Shower', 'Breakfast Included'],
    featured: false,
  },
  {
    id: '9',
    name: 'Grand Colonial Suite',
    description: 'Step back in time with this heritage-themed suite. Features antique mahogany furniture, high ceilings, and a wrap-around veranda typical of the colonial era.',
    price: 550,
    capacity: 3,
    imageUrl: '/images/rooms/room%20garden.jpg',
    slug: 'grand-colonial-suite',
    amenities: ['Antique Decor', 'Wrap-around Veranda', 'Four-Poster Bed', 'Afternoon Tea', 'Living Room', 'Bathtub'],
    featured: false,
  },
];